version: "3"
services:
  mysql:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=mysql_database
      - MYSQL_USER=user
      - MYSQL_PASSWORD=my_password
      - MYSQL_ROOT_PASSWORD=my_password
    volumes:
      - ./data/db:/var/lib/mysql

